[package]
name = "gold_2"
version = "0.1.0"
edition = "2021"

[dependencies]
# server
tokio = { version = "1.43.0", features = ["full"] }
axum = "0.8.1"
serde = "1.0.217"
serde_json = "1.0.138"

# cryptography
secp256k1 = "0.30.0"
sha2 = "0.10.8"
